/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CompomentEditGender: typeof import('./src/components/CompomentEditGender.vue')['default']
    CompomentFriendList: typeof import('./src/components/CompomentFriendList.vue')['default']
    CompomentLoginInput: typeof import('./src/components/CompomentLoginInput.vue')['default']
    ComponentAva: typeof import('./src/components/ComponentAva.vue')['default']
    ComponentEditBox: typeof import('./src/components/ComponentEditBox.vue')['default']
    ComponentEditGender: typeof import('./src/components/ComponentEditGender.vue')['default']
    ComponentEmoji: typeof import('./src/components/ComponentEmoji.vue')['default']
    COmponentEmoji: typeof import('./src/components/COmponentEmoji.vue')['default']
    ComponentLogin: typeof import('./src/components/ComponentLogin.vue')['default']
    ComponentMessage: typeof import('./src/components/ComponentMessage.vue')['default']
    ComponentMessageMy: typeof import('./src/components/ComponentMessageMy.vue')['default']
    ComponentMessageOther: typeof import('./src/components/ComponentMessageOther.vue')['default']
    ComponentMoreUserInfo: typeof import('./src/components/ComponentMoreUserInfo.vue')['default']
    ComponentMyTeam: typeof import('./src/components/ComponentMyTeam.vue')['default']
    ComponentRegister: typeof import('./src/components/ComponentRegister.vue')['default']
    ComponentTeamDetails: typeof import('./src/components/ComponentTeamDetails.vue')['default']
    ComponentUserTeams: typeof import('./src/components/ComponentUserTeams.vue')['default']
    ComponetRecomentUserInfo: typeof import('./src/components/ComponetRecomentUserInfo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamCardList: typeof import('./src/components/teamCardList.vue')['default']
    UserCardList: typeof import('./src/components/userCardList.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanStepper: typeof import('vant/es')['Stepper']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
